(if (eq system-type 'darwin)
    (lambda ()
      (add-to-list 'load-path (local-path-to "applescript"))
      (autoload 'applescript-mode "applescript-mode" "AppleScript" t)
      (setq auto-mode-alist (cons '("\\.scpt$" . applescript-mode) auto-mode-alist))
      )
)
