(auto-package-install '(multiple-cursors smartrep))

(add-to-list 'load-path (local-path-to "multiple-cursors"))
(require 'multiple-cursors)
(require 'smartrep)

(declare-function smartrep-define-key "smartrep")
(defun mc/mark-next-like-this-and-cycle-forward ()
  (interactive)
  (mc/mark-next-like-this 1)
  (mc/cycle-forward))
(defun mc/mark-previous-like-this-and-cycle-backward ()
  (interactive)
  (mc/mark-previous-like-this 1)
  (mc/cycle-backward))
(global-set-key (kbd "C-M-c") 'mc/edit-lines)
(global-set-key (kbd "C-M-r") 'mc/mark-all-in-region)
(global-unset-key "\C-t")
(smartrep-define-key global-map "C-t"
                     '(("n" . 'mc/mark-next-like-this-and-cycle-forward)
                       ("p" . 'mc/mark-previous-like-this-and-cycle-backward)
                       ("m" . 'mc/mark-more-like-this-extended)
                       ("u" . 'mc/unmark-next-like-this)
                       ("U" . 'mc/unmark-previous-like-this)
                       ("s" . 'mc/skip-to-next-like-this)
                       ("S" . 'mc/skip-to-previous-like-this)
                       ("*" . 'mc/mark-all-like-this)
                       ("d" . 'mc/mark-all-like-this-dwim)
                       ("i" . 'mc/insert-numbers)
                       ("o" . 'mc/sort-regions)
                       ("O" . 'mc/reverse-regions)))
